version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-nsfw-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.json:/app/config.json:ro
      - ./logs:/app/logs
    networks:
      - discord-bot-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  discord-bot-network:
    driver: bridge

volumes:
  bot-logs:
    driver: local
